CREATE TABLE T_TASK (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CASE_NR NUMERIC(19) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    CREATED DATETIME NOT NULL,

    PRIMARY KEY (ID)
);

CREATE INDEX IDX_TASK_CASE_NR
    ON T_TASK (CASE_NR);

