CREATE TABLE T_USER (
    ID INT,
    EMAIL VARCHAR(100),
    NAME VARCHAR(100),
    PASSWD VARCHAR(100),
    CREATED DATE,

    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_USER_EMAIL
    ON T_USER (EMAIL);

CREATE TABLE T_ROLE (
    ID INT,
    ROLE_NAME VARCHAR(100),
    USER_ID INT,

    PRIMARY KEY (ID)
);

ALTER TABLE T_ROLE
    ADD CONSTRAINT
    FK_ROLE_TO_USER
    FOREIGN KEY(USER_ID)
    REFERENCES T_USER (ID);

CREATE INDEX IDX_ROLE_USER_ID
    ON T_ROLE (USER_ID);
