DELETE FROM T_ROLE;
DELETE FROM T_USER;

INSERT INTO T_USER (ID, EMAIL, NAME, PASSWD, CREATED) VALUES (1, 'john@maxant.ch', 'John Smith', 'TODO', now());

INSERT INTO T_USER (ID, EMAIL, NAME, PASSWD, CREATED) VALUES (2, 'jane@maxant.ch', 'Jane Smith', 'TODO', now());

INSERT INTO T_ROLE (ID, ROLE_NAME, USER_ID) VALUES (1, 'ADMIN', 1);
INSERT INTO T_ROLE (ID, ROLE_NAME, USER_ID) VALUES (2, 'USER',  1);
INSERT INTO T_ROLE (ID, ROLE_NAME, USER_ID) VALUES (3, 'USER',  2);

