CREATE TABLE T_COMMAND (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    COMMAND TEXT NOT NULL,
    ATTEMPTS INT NOT NULL,
    LOCKED TIMESTAMP,
    IDEMPOTENCY_ID VARCHAR(36) NOT NULL,
    CONTEXT TEXT NOT NULL,

    PRIMARY KEY (ID)
);

